source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}" }

gem 'supplejack_api', github: 'DigitalNZ/supplejack_api', tag: 'v3.6.1'
gem 'sunspot_rails', '~> 2.2.0'
gem 'active_model_serializers', '~> 0.10.7'
gem 'mongoid_auto_increment', '~> 0.1.5'
gem 'whenever', '~> 0.10.0'
gem 'rails', '~> 5.2.0'
gem 'sqlite3', '~> 1.3.13'
gem 'puma', '~> 3.12'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
